/*
 * ShadowStrike - Enterprise NGAV/EDR Platform
 * Copyright (C) 2026 ShadowStrike Security
 */

#include "pch.h"
#include "EmbeddedRuleLoader.hpp"
#include "RulesBlobKey.hpp"
#include "RuleStore.hpp"
#include "RuleImporter.hpp"
#include "RuleParser.hpp"

#include <chrono>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace ShadowStrike::Detection {

// Declared in RulesBlob.generated.cpp (generated by tools/bake_rules.ps1).
// When no blob is compiled in, the generated file emits an empty array and
// kPhantomRulesDataSize == 0, so the loader returns 0 gracefully.
extern const unsigned char* kPhantomRulesData;
extern const size_t         kPhantomRulesDataSize;

static uint32_t readU32LE(const uint8_t* p) noexcept {
    return uint32_t(p[0])
        | (uint32_t(p[1]) << 8)
        | (uint32_t(p[2]) << 16)
        | (uint32_t(p[3]) << 24);
}

static uint16_t readU16LE(const uint8_t* p) noexcept {
    return uint16_t(p[0]) | (uint16_t(p[1]) << 8);
}

size_t LoadEmbeddedRules(RuleStore& store, ImportResult* result) {
    if (!kPhantomRulesData || kPhantomRulesDataSize == 0)
        return 0;

    // --- XOR decode into a working buffer ---
    std::vector<uint8_t> buf(kPhantomRulesDataSize);
    for (size_t i = 0; i < kPhantomRulesDataSize; ++i)
        buf[i] = kPhantomRulesData[i] ^ kRulesBlobKey[i % 32];

    const uint8_t* p   = buf.data();
    const uint8_t* end = p + buf.size();

    // --- Validate header (10 bytes: 4 magic + 2 version + 4 count) ---
    if (end - p < 10) return 0;
    if (p[0] != 'P' || p[1] != 'H' || p[2] != 'R' || p[3] != 'B') return 0;
    // p[4], p[5] = version (currently 0x01, 0x00) — reserved for future use
    uint32_t count = readU32LE(p + 6);
    p += 10;

    ImportResult r{};
    size_t total = 0;

    for (uint32_t i = 0; i < count && p < end; ++i) {
        // Per-entry layout:
        //   [1]  source_type
        //   [2]  filename_len (LE uint16)
        //   [N]  filename bytes
        //   [4]  content_len (LE uint32)
        //   [M]  content bytes
        if (end - p < 7) break;  // minimum: 1 + 2 + 0 + 4 = 7

        uint8_t  srcType = *p++;
        uint16_t fnLen   = readU16LE(p); p += 2;
        if (static_cast<ptrdiff_t>(fnLen) > end - p) break;
        std::string filename(reinterpret_cast<const char*>(p), fnLen);
        p += fnLen;

        if (end - p < 4) break;
        uint32_t contentLen = readU32LE(p); p += 4;
        if (static_cast<ptrdiff_t>(contentLen) > end - p) break;
        std::string_view content(reinterpret_cast<const char*>(p), contentLen);
        p += contentLen;

        PhantomRule rule;
        bool ok = false;
        switch (srcType) {
            case 0:  // Native phantom rules
                ok = RuleParser::ParseNativeText(content, rule);
                if (ok) { rule.source = RuleSource::Native;  r.native++;  }
                break;
            case 1:  // capa YAML rules
                ok = RuleParser::ParseCapaYaml(content, rule);
                if (ok) { rule.source = RuleSource::Capa;    r.capa++;    }
                break;
            case 2:  // Sigma YAML rules
                ok = RuleParser::ParseSigmaYaml(content, rule);
                if (ok) { rule.source = RuleSource::Sigma;   r.sigma++;   }
                break;
            case 3:  // Elastic NDJSON rules
                ok = RuleParser::ParseElasticJson(content, rule);
                if (ok) { rule.source = RuleSource::Elastic; r.elastic++; }
                break;
            default:
                break;
        }

        if (ok) {
            rule.sourceUri  = filename;
            rule.importedAt = std::chrono::system_clock::now();
            if (store.AddOrReplace(std::move(rule))) ++total;
        } else {
            ++r.errors;
        }
    }

    if (result) *result = r;
    return total;
}

} // namespace ShadowStrike::Detection
