// AUTO-GENERATED by tools/bake_rules.ps1 — DO NOT EDIT
// Contains obfuscated compiled rule data for ShadowStrike Phantom EDR.
#include "pch.h"
#include "EmbeddedRuleLoader.hpp"

namespace ShadowStrike::Detection {

alignas(8) static const unsigned char kPhantomRulesDataRaw[] = { 0x00 };
// extern forces external linkage — without it, const at namespace scope
// has internal linkage in C++ and the symbol is invisible to EmbeddedRuleLoader.obj
extern const unsigned char* kPhantomRulesData = nullptr;  // empty blob
extern const size_t kPhantomRulesDataSize = 0;

} // namespace ShadowStrike::Detection
